using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Ennui.Api.Meta
{
    public enum PlayerAttribute
    {
        HitpointsMax,
        HitpointsMaxBonus,
        HitpointsRegeneration,
        HitpointsRegenerationBonus,
        EnergyMax,
        EnergyMaxBonus,
        EnergyRegeneration,
        EnergyRegenerationBonus,
        CraftingFocusMax,
        CraftingFocusMaxBonus,
        CraftingFocusRegeneration,
        CraftingFocusRegenerationBonus,
        MoveSpeed,
        MoveSpeedBonus,
        MaxLoad,
        MaxLoadBonus,
        AttackDamage,
        PhysicalAttackDamageBonus,
        MagicAttackDamageBonus,
        AttackRangeBonus,
        AttackSpeedBonus,
        PhysicalSpellDamageBonus,
        MagicSpellDamageBonus,
        MagicCastTimeReductionRaw,
        MagicCastTimeReductionAdjusted,
        MagicCoolDownReductionRaw,
        MagicCoolDownReductionAdjusted,
        MagicCastingResilience,
        HealBonus,
        HealModifier,
        EnergyCostReduction,
        PhysicalArmor,
        MagicResistance,
        CrowdControlResistance,
        BalanceModifier,
        FocusFireModifier,
        HealingSicknessModifier,
        FocusFireProtectionPeneration,
        CraftTime,
        InstallTime,
        GatheringSpeed,
        GatheringYield,
        BonusDamageVsPlayers,
        BonusDefenseVsPlayers,
        BonusCCRVsPlayers,
        BonusCCDurationVsPlayers,
        BonusDamageVsMobs,
        BonusDefenseVsMobs,
        BonusCCRVsMobs,
        BonusCCDurationVsMobs,
        CrowdControlDiminishingReturn,
        CraftingQuality,
        CraftingFocusCostReduction,
        AbilityPower,
        AbilityPowerBonus,
        ItemPower,
        ThreatBonus,
        NumAttributes

    }
}
